apiVersion: apps/v1
kind: Deployment
metadata:
  name:  MYAPP
  namespace:  dev
  labels:
    app:  MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  replicas: 1
  template:
    metadata:
      labels:
        app:  MYAPP
    spec:
      containers:
      - name:  MYAPP
        image:  caothi/cicd:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8000
          name:  MYAPP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: MyApp_service
  namespace: dev
spec:
  selector:
    app: MYAPP
  type: ClusterIP
  ports:
  - name: MYAPP
    protocol: TCP
    port: 80
    targetPort: 8000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: IngressName
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: MyApp_service
            port:
              number: 80